import os

# API base
API_LOCAL_URL = os.getenv("API_LOCAL_URL")

# ALTAS
TOKEN_ALTAS = os.getenv("TOKEN_ALTAS")
TOKEN_ALTAS2 = os.getenv("TOKEN_ALTAS2")
TOKEN_BAJAS = os.getenv("TOKEN_BAJAS")

# ANEXO
TOKEN_ANEXO = os.getenv("TOKEN_ANEXO")
TOKEN_ANEXO2 = os.getenv("TOKEN_ANEXO2")

# WALMART
TOKEN_DOC_FIRMA_WALMART = os.getenv("TOKEN_DOC_FIRMA_WALMART")
TOKEN_DOC_CARPETA_WALMART = os.getenv("TOKEN_DOC_CARPETA_WALMART")
TOKEN_ASISTENCIA_WALMART = os.getenv("TOKEN_ASISTENCIA_WALMART")
# Históricamente transferencias usaba el mismo token de asistencia en este proyecto
TOKEN_TRANSFERENCIAS_WALMART = os.getenv("TOKEN_ASISTENCIA_WALMART")

# TELEFÓNICA (placeholders)
TOKEN_DOC_FIRMA_TELEFONICA = os.getenv("TOKEN_DOC_FIRMA_TELEFONICA")
TOKEN_DOC_CARPETA_TELEFONICA = os.getenv("TOKEN_DOC_CARPETA_TELEFONICA")
TOKEN_ASISTENCIA_TELEFONICA = os.getenv("TOKEN_ASISTENCIA_TELEFONICA")
TOKEN_TRANSFERENCIAS_TELEFONICA = os.getenv("TOKEN_TRANSFERENCIAS_TELEFONICA")

# SSOMA / SANTO TOMAS (placeholders)
TOKEN_DOC_FIRMA_SANTOTOMAS = os.getenv("TOKEN_DOC_FIRMA_SANTOTOMAS")
TOKEN_DOC_CARPETA_SANTOTOMAS = os.getenv("TOKEN_DOC_CARPETA_SANTOTOMAS")
TOKEN_ASISTENCIA_SANTOTOMAS = os.getenv("TOKEN_ASISTENCIA_SANTOTOMAS")
TOKEN_TRANSFERENCIAS_SANTOTOMAS = os.getenv("TOKEN_TRANSFERENCIAS_SANTOTOMAS")

# ARIBA / INDUMOTORA (placeholders)
TOKEN_DOC_FIRMA_INDU = os.getenv("TOKEN_DOC_FIRMA_INDU")
TOKEN_DOC_CARPETA_INDU = os.getenv("TOKEN_DOC_CARPETA_INDU")
TOKEN_ASISTENCIA_INDU = os.getenv("TOKEN_ASISTENCIA_INDU")
TOKEN_TRANSFERENCIAS_INDU = os.getenv("TOKEN_TRANSFERENCIAS_INDU")

# CERTILAB / UNIMARC (placeholders)
TOKEN_DOC_FIRMA_UNIMARC = os.getenv("TOKEN_DOC_FIRMA_UNIMARC")
TOKEN_DOC_CARPETA_UNIMARC = os.getenv("TOKEN_DOC_CARPETA_UNIMARC")
TOKEN_ASISTENCIA_UNIMARC = os.getenv("TOKEN_ASISTENCIA_UNIMARC")
TOKEN_TRANSFERENCIAS_UNIMARC = os.getenv("TOKEN_TRANSFERENCIAS_UNIMARC")

# OVAL / SENIORSUITES (placeholders)
TOKEN_DOC_FIRMA_SENIORSUITES = os.getenv("TOKEN_DOC_FIRMA_SENIORSUITES")
TOKEN_DOC_CARPETA_SENIORSUITES = os.getenv("TOKEN_DOC_CARPETA_SENIORSUITES")
TOKEN_ASISTENCIA_SENIORSUITES = os.getenv("TOKEN_ASISTENCIA_SENIORSUITES")
TOKEN_TRANSFERENCIAS_SENIORSUITES = os.getenv("TOKEN_TRANSFERENCIAS_SENIORSUITES")

